/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package IU;

import BEAN.Cliente;
import BEAN.Vendedor;
import DAO.VendedorDAO;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import IU.frmVendedor;
import IU.frmTiendaRopa;
import java.awt.Dimension;
import java.awt.Toolkit;
/**
 *
 * @author Jorge
 */
public class dlgVendedor extends javax.swing.JDialog {
    VendedorDAO VDao;
    DefaultTableModel dtm;
    Vendedor vend;
    String idRep;
    

    /** Creates new form dlgVendedor */
    public dlgVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        VDao = new VendedorDAO();        
        initComponents();
        vend= new Vendedor();
        
        
        dtm = (DefaultTableModel) this.tblVendedord.getModel();
        llenaTblVendedor(false, "");  
        int wd, hd, slx, sly;
        Toolkit toolkit =  Toolkit.getDefaultToolkit ();
        Dimension dim = toolkit.getScreenSize();
        wd = dim.width;
        hd = dim.height;
        this.setSize(445, 295);
        slx = (wd/2) - (200);
        sly = (hd/2) -(250);
        this.setLocation(slx, sly);
        this.setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarRepartidor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVendedord = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("Vendedores");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(168, 11, 97, 25);

        jLabel2.setText("Buscar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(51, 45, 32, 14);

        txtBuscarRepartidor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarRepartidorKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscarRepartidor);
        txtBuscarRepartidor.setBounds(126, 42, 220, 20);

        tblVendedord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre completo", "Telefono", "Direccion"
            }
        ));
        tblVendedord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVendedordMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVendedord);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 417, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Vendedor getVend() {
        return this.vend;
    }

    
    private void llenaTblVendedor(boolean sw, String cad) {
   
    Vector<Vendedor> listProd = this.VDao.ListaItem(sw, cad);
        dtm.setRowCount(0);
        for (int i = 0; i < listProd.size(); i++) {
            Vector vRep = new Vector();
            vRep.addElement(listProd.get(i).getDniVendedor());
            vRep.addElement(listProd.get(i).getNombVendedor());
            vRep.addElement(listProd.get(i).getTelefono());
            vRep.addElement(listProd.get(i).getDireccion());
            vRep.addElement(listProd.get(i).getDistrito());
            vRep.addElement(listProd.get(i).getSueldo());
            dtm.addRow(vRep);
        }
    }
    private void txtBuscarRepartidorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarRepartidorKeyReleased
        if (this.txtBuscarRepartidor.getText().isEmpty()) {
            llenaTblVendedor(false, "");
        } else {
            llenaTblVendedor(true, this.txtBuscarRepartidor.getText());
        }
    }//GEN-LAST:event_txtBuscarRepartidorKeyReleased

    private void tblVendedordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVendedordMouseClicked
      int fil;
        fil = this.tblVendedord.getSelectedRow();
        vend = new Vendedor();
        //this.idP Integer.parseInt(dtm.getValueAt(fil, 0).toString());
        this.vend.setDniVendedor(dtm.getValueAt(fil, 0).toString());
        
      dispose();
    }//GEN-LAST:event_tblVendedordMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVendedord;
    private javax.swing.JTextField txtBuscarRepartidor;
    // End of variables declaration//GEN-END:variables

}
