/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

/**
 *
 * @author RAUL
 */
public class frmRegistrarVenta extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistrarVenta
     */
    public frmRegistrarVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField52 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField57 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jTextField58 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jTextField59 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Seleccionar producto");
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 20, 150, 32);

        jButton2.setText("Seleccionar repartidor");
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 180, 150, 32);

        jButton3.setText("Seleccionar Cliente");
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 20, 150, 32);

        jButton4.setText("Seleccionar Vended");
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 80, 150, 32);

        jButton5.setText("Seleccionar pago");
        getContentPane().add(jButton5);
        jButton5.setBounds(230, 80, 150, 32);

        jButton6.setText("Seleccionar delivery");
        getContentPane().add(jButton6);
        jButton6.setBounds(30, 180, 150, 32);

        jPanel17.setLayout(null);

        jLabel7.setText("PRODUCTOS PEDIDOS");
        jPanel17.add(jLabel7);
        jLabel7.setBounds(10, 0, 190, 16);
        jPanel17.add(jTextField52);
        jTextField52.setBounds(80, 110, 50, 24);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Monto");
        jPanel17.add(jLabel10);
        jLabel10.setBounds(30, 110, 40, 20);

        jButton7.setText("Calcular");
        jPanel17.add(jButton7);
        jButton7.setBounds(160, 90, 110, 40);

        jButton8.setText("Seleccionar");
        jPanel17.add(jButton8);
        jButton8.setBounds(160, 20, 110, 40);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProducto", "Precio", "Cantidad", "Monto"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel17.add(jScrollPane3);
        jScrollPane3.setBounds(20, 210, 240, 120);
        jPanel17.add(jTextField57);
        jTextField57.setBounds(80, 20, 70, 24);

        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel70.setText("Codigo");
        jPanel17.add(jLabel70);
        jLabel70.setBounds(10, 20, 60, 20);
        jPanel17.add(jTextField58);
        jTextField58.setBounds(80, 50, 50, 24);

        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel71.setText("Precio");
        jPanel17.add(jLabel71);
        jLabel71.setBounds(10, 50, 60, 20);
        jPanel17.add(jTextField59);
        jTextField59.setBounds(80, 80, 50, 24);

        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel72.setText("Cantidad");
        jPanel17.add(jLabel72);
        jLabel72.setBounds(10, 80, 60, 20);

        jButton17.setText("Agregar");
        jPanel17.add(jButton17);
        jButton17.setBounds(100, 150, 110, 40);

        getContentPane().add(jPanel17);
        jPanel17.setBounds(420, 10, 280, 340);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(250, 120, 110, 26);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(50, 120, 110, 26);

        jButton9.setText("Guardar pedido");
        getContentPane().add(jButton9);
        jButton9.setBounds(180, 310, 130, 32);

        setSize(new java.awt.Dimension(729, 398));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistrarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    // End of variables declaration//GEN-END:variables
}
